# Change these first
owner: falkben # Your GitHub organization or username, where this repository lives
repo: mast-status # The name of this repository

sites:
  - name: Archive
    url: https://archive.stsci.edu
  - name: Tesscut
    url: https://mast.stsci.edu/tesscut
  - name: Portal
    url: https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html
  - name: HST Search
    url: https://mast.stsci.edu/search/hst/ui/#/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /mast-status
  logoUrl: https://outerspace.stsci.edu/download/attachments/91624098/MASTDATA?version=1&modificationDate=1614887543937&api=v2
  name: MAST Status Page
  introTitle: "(DEMO) Status page for MAST services"
  introMessage: Real time data powered by github actions
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
